# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CongressRestaurantMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opendataday.CongressMan')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=250)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='congressrestaurantmap',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opendataday.Restaurant'),
        ),
    ]
